# Generated by Django 4.1.4 on 2022-12-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minimum_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
