# Generated by Django 4.1.4 on 2022-12-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
