# Generated by Django 3.2.12 on 2022-12-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0006_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
