# Generated by Django 3.2.12 on 2022-12-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
