# Generated by Django 3.2.12 on 2022-12-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default='False'),
        ),
    ]
