# Generated by Django 3.2.12 on 2022-12-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0012_alter_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
