# Generated by Django 3.2.12 on 2023-01-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0015_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Stripe', 'Stripe')], default='Cash On Delivery', max_length=20),
        ),
    ]
