# Generated by Django 3.2.12 on 2023-01-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolsapp', '0017_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
